//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPP_Assignment.Admin
{
    public partial class Admin
    {
        /// <summary>
        /// adminForm control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm adminForm;

        /// <summary>
        /// lnkDashboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkDashboard;

        /// <summary>
        /// lnkUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkUsers;

        /// <summary>
        /// lnkCourses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkCourses;

        /// <summary>
        /// HeadAdmin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadAdmin;

        /// <summary>
        /// AdminMain control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder AdminMain;
    }
}
