//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPP_Assignment.Admin
{


    public partial class AdminForcePasswordReset
    {

        /// <summary>
        /// litUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUsername;

        /// <summary>
        /// txtNewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;

        /// <summary>
        /// litErrorPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litErrorPassword;

        /// <summary>
        /// txtConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        /// <summary>
        /// litErrorConfirm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litErrorConfirm;

        /// <summary>
        /// litErrorGeneral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litErrorGeneral;

        /// <summary>
        /// btnChangePassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnChangePassword;
    }
}
