//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPP_Assignment.Lecturer
{
    public partial class LecturerCourseEditor
    {
        protected global::System.Web.UI.WebControls.Literal litCourseTitle;

        protected global::System.Web.UI.WebControls.HyperLink lnkBackDetails;

        protected global::System.Web.UI.WebControls.Label lblInfo;

        protected global::System.Web.UI.WebControls.Panel pnlEditor;

        protected global::System.Web.UI.WebControls.HiddenField hfCourseId;

        protected global::System.Web.UI.WebControls.Repeater rptChapters;

        protected global::System.Web.UI.WebControls.TextBox txtNewChapterTitle;

        protected global::System.Web.UI.WebControls.Button btnAddChapter;
    }
}
