//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPP_Assignment.Lecturer
{
    public partial class LecturerDashboard
    {
        /// <summary>
        /// litDashboardSubtitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDashboardSubtitle;

        /// <summary>
        /// litProfileName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProfileName;

        /// <summary>
        /// litProfileRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProfileRole;

        /// <summary>
        /// litProfileEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litProfileEmail;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        /// <summary>
        /// litCoursesCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCoursesCount;

        /// <summary>
        /// litAssessmentsCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAssessmentsCount;

        /// <summary>
        /// litExercisesCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litExercisesCount;

        /// <summary>
        /// litQuestionsCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litQuestionsCount;

        /// <summary>
        /// litStudentsCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStudentsCount;

        /// <summary>
        /// litEnrollmentsCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEnrollmentsCount;

        /// <summary>
        /// litAvgProgress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAvgProgress;

        /// <summary>
        /// litTopCourseTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTopCourseTitle;

        /// <summary>
        /// litTopCourseEnrollments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTopCourseEnrollments;

        /// <summary>
        /// lblCoursesEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCoursesEmpty;

        /// <summary>
        /// rptRecentCourses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRecentCourses;

        /// <summary>
        /// lblAssessmentsEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAssessmentsEmpty;

        /// <summary>
        /// rptRecentAssessments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRecentAssessments;
    }
}
