//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPP_Assignment.Lecturer
{
    public partial class LecturerCourseDetails
    {
        /// <summary>
        /// litCourseTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCourseTitle;

        /// <summary>
        /// lnkEditCourse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkEditCourse;

        /// <summary>
        /// litCourseMeta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCourseMeta;

        /// <summary>
        /// litCourseDesc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCourseDesc;

        /// <summary>
        /// rptChapters control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptChapters;

        /// <summary>
        /// lblInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblInfo;
    }
}
