//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPP_Assignment.Lecturer
{
    public partial class LecturerCourseBuilder
    {
        protected global::System.Web.UI.WebControls.Label lblStatus;

        protected global::System.Web.UI.WebControls.DropDownList ddlCourses;

        protected global::System.Web.UI.WebControls.HiddenField hfCourseId;

        protected global::System.Web.UI.WebControls.HiddenField hfCurrentCourseImgUrl;

        protected global::System.Web.UI.WebControls.TextBox txtCourseTitle;

        protected global::System.Web.UI.WebControls.TextBox txtCourseDescription;

        protected global::System.Web.UI.WebControls.FileUpload fuCourseImg;

        protected global::System.Web.UI.WebControls.CheckBox chkRemoveImg;

        protected global::System.Web.UI.WebControls.Image imgPreview;

        protected global::System.Web.UI.WebControls.Button btnNewCourse;

        protected global::System.Web.UI.WebControls.Button btnSaveCourse;

        protected global::System.Web.UI.WebControls.Button btnDeleteCourse;
    }
}
