//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPP_Assignment.Lecturer
{
    public partial class LecturerCourseDetails
    {
        protected global::System.Web.UI.WebControls.Literal litCourseTitle;
        protected global::System.Web.UI.WebControls.Literal litCourseMeta;
        protected global::System.Web.UI.WebControls.Literal litCourseDesc;
        protected global::System.Web.UI.WebControls.Repeater rptChapters;
        protected global::System.Web.UI.WebControls.Label lblInfo;
    }
}
