//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAPP_Assignment.Lecturer
{
    public partial class LecturerMaster
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// HeadLecturer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadLecturer;

        /// <summary>
        /// LecturerMain control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder LecturerMain;
    }
}
