//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WAPP_Assignment.Lecturer
{
    public partial class LecturerAssessmentDetails
    {
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litMeta;

        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.Button btnSaveTitle;
        protected global::System.Web.UI.WebControls.Label lblMsg;

        protected global::System.Web.UI.WebControls.Repeater rptQuestions;

        protected global::System.Web.UI.WebControls.DropDownList ddlExercise;
        protected global::System.Web.UI.WebControls.Button btnAddAllFromExercise;
        protected global::System.Web.UI.WebControls.Repeater rptExerciseQuestions;

        protected global::System.Web.UI.WebControls.Label lblInfo;
    }
}
